import json
import re
import pandas as pd

class OutputCleaner:
    """ Designed to post-process and repair JSON-like outputs generated by LLMs. 
    Model outputs often contain formatting artefacts such as markdown code blocks (```json), <think> tags, None values, 
    malformed list structures, unnecessary location keys ("continent:", "country:"...) or duplicated or missing quotation marks. 
    The class provides a pipeline that attempts to clean, normalize, and parse the content into valid JSON. """

    @staticmethod
    def sanitize_list_elements(text):
        """
        Ensure all elements within lists are properly quoted strings.
        Ensures:
            - each list element is quoted once
            - extra or duplicated quotes are removed
            - whitespace around items is trimmed"""
        def fix_list(match):
            # Assumes list items are correctly delimited by commas
            items = match.group(1).split(',')
            clean_items = []
            for item in items:
                item = item.strip()
                # Remove duplicated quotes
                if item.count('"') > 2:
                    item = item.replace('"', '')
                    item = f'"{item.strip()}"'
                # Add quotes if missing
                elif not item.startswith('"'):
                    item = f'"{item.strip()}"'
                clean_items.append(item)
            return '[' + ', '.join(clean_items) + ']'
            

        return re.sub(r'\[(.*?)\]', fix_list, text, flags=re.DOTALL)

    @staticmethod
    def clean_output_field(text):
        """
        Remove noise added by LLMs before attempting JSON parsing (<think> tags, markdown code blocks, None values).
        """
        text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
        text = re.sub(r'```json\s*', '', text)
        text = re.sub(r'```', '', text)
        text = re.sub(r':\s*None\b', ': null', text)
        return text.strip()

    @staticmethod
    def extract_residence_values(raw_list):
        """Extracts residence values from a malformed list string."""
        results = []
        key_vals = re.findall(r'"[^"]+"\s*:\s*(\[[^\]]+\]|"[^"]*"|None)', raw_list)
        for val in key_vals:
            val = val.strip().strip('" ')
            if val.startswith("["):
                try:
                    sublist = json.loads(val)
                    results.extend(sublist)
                except Exception:
                    continue
            else:
                results.append(val)
        return results

    @staticmethod
    def remove_location_keys(text):
        """
        Remove unwanted location prefixes such as 'continent', 'country', 'state', 'city' from the text.
        """
        keys_to_remove = [
            r'continent\s*: ',
            r'country\s*: ',
            r'state\s*: ',
            r'city\s*: ',
            r'any other available location information\s*:' 
        ]
        for pattern in keys_to_remove:
            text = re.sub(pattern, '', text)
        text = text.replace('" [', '"')
        #text = text.replace('},', ',')
        text = text.replace(']],', '],')
        text = re.sub(r'\]\s*\],', '],', text)
        text = text.replace('[""] ', '[""],')
        text = re.sub(r'("\])\s*(")', r'\1,\n\2', text)
        return text

    @staticmethod
    def extract_last_json(output_field, attribute='residence', list_attributes=None):
        """
        Main function:
            - Attempts to extract the last JSON block from an LLM output.
            - Applies multiple normalization steps until parsing succeeds.
            - If the JSON is malformed specifically in the target attribute (e.g., residence),
              a fallback mechanism reconstructs a clean list of values.

        Parameters
        ----------
        output_field : str
            The raw LLM output.
        attribute : str
            Primary attribute to repair if the JSON is partially broken.
        list_attributes : list[str]
            Attributes expected to be present in the JSON. If parsing fails, a fallback dict with these attributes set to None is returned.

        Returns
        -------
        dict | None
            Parsed JSON dict or a fallback dict with None values.
        """
        if not isinstance(output_field, str):
            return {attribute: None for attribute in list_attributes}
        
        output_field = OutputCleaner.clean_output_field(output_field)
        json_text = output_field.strip()

        match = re.search(r'(\{[\s\S]*\})\s*$', output_field)
        if match:
            json_text = match.group(1)
            # Origin specific fixes
            json_text = re.sub(
                r'"origin"\s*:\s*\[\s*((?:"[^"]+"\s*:\s*"[^"]+",?\s*)+)\]',
                lambda m: '"origin": [' + ', '.join(
                    f'"{val}"' for val in re.findall(r':\s*"([^"]+)"', m.group(1))
                ) + ']',
                json_text
            )

            json_text = re.sub(
                r'"origin"\s*:\s*\[[^\[\]]+\]\s*:\s*(\[[^\[\]]+\])',
                r'"origin": \1',
                json_text,
                flags=re.DOTALL
            )

            try:
                json_text = re.sub(r'\[(.*?)\]', lambda m: '[' + ', '.join(
                    f'"{x.strip()}"' if not re.match(r'^\s*"[^"]*"\s*$', x.strip()) else x.strip()
                    for x in m.group(1).split(',')
                ) + ']', json_text)
                json_text = OutputCleaner.sanitize_list_elements(json_text)
                json_text = OutputCleaner.remove_location_keys(json_text)
                json_text = re.sub(r'\["\["([^"]+)"+"', r'["\1"', json_text)
                json_text = re.sub(r"'null',", '', json_text)
                return json.loads(json_text)
            except json.JSONDecodeError as e:
                try:
                    broken_match = re.search(rf'"{attribute}"\s*:\s*\[(.*?)\](,|\n)', json_text, re.DOTALL)
                    if broken_match:
                        raw_list = broken_match.group(1)
                        fixed_res_list = OutputCleaner.extract_residence_values(raw_list)
                        fixed_res_str = json.dumps(fixed_res_list, ensure_ascii=False)
                        json_text = re.sub(rf'"{attribute}"\s*:\s*\[.*?\](,|\n)', f'"{attribute}": {fixed_res_str}\\1', json_text, flags=re.DOTALL)
                        json_text = re.sub(r'\[(.*?)\]', lambda m: '[' + ', '.join(
                            f'"{x.strip()}"' if not re.match(r'^\s*"[^"]*"\s*$', x.strip()) else x.strip()
                            for x in m.group(1).split(',')
                        ) + ']', json_text)
                        json_text = OutputCleaner.sanitize_list_elements(json_text)
                        json_text = OutputCleaner.remove_location_keys(json_text)
                        json_text = re.sub(r'\["\["([^"]+)"+"', r'["\1"', json_text)
                        # replace "'null'," with ""
                        json_text = re.sub(r"'null',", '', json_text)
                        return json.loads(json_text)
                except Exception as fix_err:
                    print(f"[Fix Error] Failed to auto-correct JSON: {fix_err}")
                    print(f"[Error] JSON Decode Error: {e} in text: {json_text}")
        print(f"[Warning] No valid JSON found or could not correct: {json_text}")
        return {attribute: None for attribute in list_attributes} if list_attributes else None

    @staticmethod
    def extract_last_part(predicted_df, attribute='residence', list_attributes=None):
        """
        Apply extract_last_json to each row of a dataframe column named 'Output', and add a column for the cleaned json (if possible),
        and a column by attribute required, filled with the extracted information.
        """

        # print all keys 
        predicted_df['parsed_output'] = predicted_df['Output'].apply(
            OutputCleaner.extract_last_json,
            args=(attribute, list_attributes,)
        )

        if list_attributes:
            for attr in list_attributes:
                predicted_df[attr] = predicted_df['parsed_output'].apply(lambda x: x.get(attr) if x else None)

        return predicted_df

# Gold cleaning function
def split_list(lang_str):
    """
    Split a comma-separated string into a clean Python list.
    Used for gold annotations extracted from spreadsheets.
    """
    if pd.isna(lang_str):
        return []
    if isinstance(lang_str, int):
        print(lang_str)
    return [l.strip() for l in lang_str.split(',') if l.strip()]

